services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PHP_VERSION: "8.3"
        NODE_VERSION: "20"
    image: laravel-app:latest
    container_name: app
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - .:/var/www/html
      - vendor:/var/www/html/vendor     # giữ vendor trong container, tránh bị bind đè
      - storage:/var/www/html/storage   # (khuyên dùng) tránh lỗi quyền trên Windows
    depends_on:
      - db
      - redis

  nginx:
    image: nginx:alpine
    container_name: web
    restart: unless-stopped
    ports:
      - "127.0.0.1:8333:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro  # ⬅️ đúng đường dẫn bạn đang dùng
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-laravel}
      MYSQL_USER: ${DB_USERNAME:-laravel}
      MYSQL_PASSWORD: ${DB_PASSWORD:-secret}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-root}
      TZ: Asia/Ho_Chi_Minh
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db                 # tên service MySQL
      PMA_PORT: 3306
      PMA_ARBITRARY: 0             # 0: chỉ server định sẵn, 1: cho phép nhập server thủ công
      UPLOAD_LIMIT: 64M
    ports:
      - "0.0.0.0:8080:80"        # map lên localhost:8080 (chỉ truy cập từ máy host)
    depends_on:
      - db    

volumes:
  dbdata:
  vendor:
  storage:
