name: Deploy to VPS on push to main

on:
  push:
    branches: [ main ]     # Tự deploy khi có code mới vào main
  workflow_dispatch:
    inputs:
      fresh:
        description: "Run migrate:fresh --seed --force (⚠️ XÓA TOÀN BỘ BẢNG)"
        required: false
        default: "false"

concurrency:
  group: deploy-main
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH into VPS and deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script_stop: true
          script: |
            set -Eeuo pipefail

            APP_DIR="${APP_DIR:-/root/tvuchatbot}"
            echo "[0/9] cd $APP_DIR"
            cd "$APP_DIR"

            echo "[1/9] Pull latest main"
            git fetch --all
            git reset --hard origin/main

            echo "[2/9] Build Docker image(s)"
            docker compose build --no-cache app

            echo "[3/9] Up containers"
            docker compose up -d --remove-orphans

            echo "[4/9] Laravel optimize & cache"
            docker compose exec -T app php artisan optimize:clear
            docker compose exec -T app php artisan config:cache
            docker compose exec -T app php artisan route:cache

            echo "[5/9] Run migrations (SAFE: no drop)"
            # Không xoá dữ liệu nếu migrate lỗi
            docker compose exec -T app php artisan migrate --force || {
              echo "⚠️ migrate --force lỗi, giữ nguyên DB"; 
            }

            if [ "${{ github.event.inputs.fresh }}" = "true" ]; then
              echo "[6/9] ⚠️ fresh requested via manual workflow_dispatch"
              echo "      → Backup DB trước khi fresh"

              TS="$(date +'%Y%m%d_%H%M%S')"
              docker compose exec -T db sh -lc 'mysqldump -uroot -p"$MYSQL_ROOT_PASSWORD" "$MYSQL_DATABASE"' > "backup_${TS}.sql"
              echo "✅ Backup saved: backup_${TS}.sql"

              echo "[7/9] Running migrate:fresh --seed --force (DROPS ALL TABLES)"
              docker compose exec -T app php artisan migrate:fresh --seed --force
            fi

            echo "[8/9] Show running services"
            docker compose ps

            echo "[9/9] ✅ Deploy completed successfully!"
        env:
          APP_DIR: ${{ secrets.APP_DIR }}
