name: Deploy to VPS on push to main

on:
  push:
    branches: [ main ]      # Tự động chạy khi có commit/merge vào main
  workflow_dispatch: {}     # Cho phép chạy thủ công từ tab Actions

concurrency:
  group: deploy-main
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH into VPS and deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VPS_HOST }}            # ví dụ 103.x.x.x
          username: ${{ secrets.VPS_USER }}        # root (hoặc user deploy)
          key: ${{ secrets.VPS_SSH_KEY }}          # private key OpenSSH
          script: |
            set -e
            cd "${APP_DIR:-/root/tvuchatbot}"

            echo "[1/6] Pull latest main"
            git fetch --all
            git reset --hard origin/main

            echo "[2/6] Build Docker image(s)"
            # Bạn đang có Docker Compose v2, dùng lệnh 'docker compose'
            docker compose build --no-cache app

            echo "[3/6] Restart containers"
            docker compose up -d --remove-orphans

            echo "[4/6] Laravel optimize & cache"
            # -T: không yêu cầu TTY khi chạy trong môi trường CI
            docker compose exec -T app php artisan optimize:clear
            docker compose exec -T app php artisan config:cache
            docker compose exec -T app php artisan route:cache

            echo "[5/6] Run migrations"
            # Nếu DB lên chậm, có thể mở sleep
            # sleep 5
            docker compose exec -T app php artisan migrate --force

            echo "[6/6] ✅ Deploy completed successfully!"
